[package]
name = "tvm-x86_64-pc"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
boot-info.workspace = true

[lints]
workspace = true
