[package]
name = "tvm_loader-x86-common"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tvm_loader.workspace = true

x86-common.workspace = true

[lints]
workspace = true
