[package]
name = "tvm_loader-uefi"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tvm_loader.workspace = true

concurrency.workspace = true
uefi.workspace = true

[lints]
workspace = true
