[package]
name = "font-converter"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
font = { workspace = true, features = [ "std" ] }

simple-psf = "0.1.2"

[lints]
workspace = true
